version: '3'

services:
  app:
    image: 'estate:latest'
    build:
      context: .
    container_name: estate
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://real-estate:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=toor
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: real-estate
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toor
    ports:
      - 5432:5432
